name: Build Twitter Scraper

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  build-twitter-scraper:
    name: build-twitter-scraper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Build package
        run: pip install build && python -m build
