name: Run Twitter Scraper

on:
  workflow_dispatch:
    inputs:
      module_name:
        type: string
        required: true
        description: "Name of the Python module to run"
        default: twitter_scraper

env:
  DEBUG: false
  USE_GPU: true
  CUDA_VISIBLE_DEVICES: 2
  NUMEXPR_MAX_THREADS: 9
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  CLASSLA_RESOURCES_DIR: '/srv/milky/classla_resources'
  STANZA_RESOURCES_DIR: '/srv/milky/stanza_resources'
  TWITTER_SCRAPER_DATA_DIR: '/srv/milky/twitter_scraper'
  FOLDER_NAME: $(date +%Y-%m-%d)

jobs:
  run-twitter-scraper:
    name: run-twitter-scraper
    runs-on: self-hosted
    timeout-minutes: 14400
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      
      - run: |
          git checkout master
          git pull origin master
          pip install --upgrade .
      
      # Runs a set of commands using the runners shell
      - name: Run Twitter Scraper
        run: python -m ${{ inputs.module_name }}
