name: Run Twitter Scraper

on:
  workflow_dispatch:

env:
  DEBUG: false
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  TWITTER_SCRAPER_DIR: '/home/milky/infocov/twitter_scraper'

jobs:
  run-twitter-scraper:
    name: run-twitter-scraper
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      
      - run: pip install ${{ env.TWITTER_SCRAPER_DIR }}
      
      # Runs a set of commands using the runners shell
      - name: Run Twitter Scraper
        run: python -m twitter_scraper
