name: Run Twitter Scraper

on:
  workflow_dispatch:
    inputs:
      module_name:
        type: string
        required: true
        description: "Name of the Python module to run"
        default: twitter_scraper

env:
  DEBUG: false
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  TWITTER_SCRAPER_DIR: '/home/milky/infocov/twitter_scraper'

jobs:
  run-twitter-scraper:
    name: run-twitter-scraper
    runs-on: self-hosted
    timeout-minutes: 14400
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      
      - run: pip install .
      
      # Runs a set of commands using the runners shell
      - name: Run Twitter Scraper
        run: python -m ${{ inputs.module_name }}
